/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author raunak
 */
public class RequestLabTestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLabTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        
        lblValueEnterprise.setText(enterprise.getName());
        lblValueDoctor.setText(account.getEmployee().getFullName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequest = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblValueEnterprise = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblValueDoctor = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTestName = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRequest.setText("Request Test");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });
        add(btnRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        lblMessage.setText("Message:");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 150, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblValueEnterprise.setText("<value>");
        add(lblValueEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 130, -1));

        lblEnterprise.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnterprise.setText("EnterPrise :");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        lblTitle.setText("Lab Requests - Dr.");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        lblValueDoctor.setText("<value>");
        add(lblValueDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jLabel1.setText("Test name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
        add(txtTestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        
        String message = txtMessage.getText();
        
        LabTestWorkRequest request = new LabTestWorkRequest();
        request.setLabTestName(txtTestName.getText());
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof LabOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            // org.getWorkQueue().getWorkRequestList().add(request);
            // userAccount.getWorkQueue().getWorkRequestList().add(request);
            
            org.getLabWorkQueue().getLabWorkRequestList().add(request);
            userAccount.getLabQueue().getLabWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(this, "Your request has been sent.");
        
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DrLabRequestJPanel dlrjp = (DrLabRequestJPanel) component;
        dlrjp.populateRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValueDoctor;
    private javax.swing.JLabel lblValueEnterprise;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtTestName;
    // End of variables declaration//GEN-END:variables
}
